name: Setup
description: |
  Setup for the project.
  This action is used to install dependencies and run the mise action.

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0

    - name: Install deps
      shell: bash
      run: bun install
