name: Setup
description: |
  Setup for the project.
  This action is used to install dependencies and run the mise action.

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

    - name: Install deps
      shell: bash
      run: bun install
