name: Setup
description: |
  Setup for the project.
  This action is used to install dependencies and run the mise action.

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0

    - name: Install deps
      shell: bash
      run: bun install
