name: Setup
description: |
  Setup for the project.
  This action is used to install dependencies and run the mise action.

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

    - name: Install deps
      shell: bash
      run: bun install
