name: Setup
description: |
  Setup for the project.
  This action is used to install dependencies and run the mise action.

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/mise-action
    - name: mise action
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

    - name: Install deps
      shell: bash
      run: bun install
