name: Preview

on:
  workflow_call:
    inputs:
      gh-app-id:
        required: true
        type: string
      ref:
        required: true
        type: string
      pr_data:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true
      cloudflare-account-id:
        required: true
      cloudflare-api-token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

        # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ inputs.gh-app-id }}
          private-key: ${{ secrets.gh-app-private-key }}

      # https://github.com/marketplace/actions/comment-pull-request
      - uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying page with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            :dancer: Now building ${{ github.sha }} ... :dancer:

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment-tag: deploy-preview
          mode: upsert

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build & Deploy Preview
        id: deploy
        uses: ./.github/actions/build-deploy
        with:
          project-name: ishinovacojp
          branch: ${{ inputs.ref }}
          cloudflare-account-id: ${{ secrets.cloudflare-account-id }}
          cloudflare-api-token: ${{ secrets.cloudflare-api-token }}

      # https://github.com/marketplace/actions/comment-pull-request
      - if: steps.deploy.outcome == 'success'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying page with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }} (i.e. ${{ fromJson(inputs.pr_data).headRefOid }} on preview)
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;✅&nbsp; Deploy successful!</td></tr>
            <tr><td><strong>Preview URL:</strong></td><td>
            <a href='${{ steps.deploy.outputs.deployment-url }}'>${{ steps.deploy.outputs.deployment-url }}</a>
            </td></tr>
            </table>

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment-tag: deploy-preview
          mode: recreate

      # https://github.com/marketplace/actions/comment-pull-request
      - if: failure()
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          message: |
            ## Deploying page with &nbsp;<a href="https://pages.dev">Cloudflare Pages</a>

            <table><tr><td><strong>Latest commit:</strong> </td><td>
            ${{ github.sha }}
            </td></tr>
            <tr><td><strong>Status:</strong></td><td>&nbsp;:warning:&nbsp; ${{ steps.deploy.outcome == 'failure' && 'Deploy' || '**Job**' }} failure!</td></tr>
            </table>

            Check the run result and/or Cloudflare Pages.

            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">github actions run **${{ github.run_id }}**</a>
          comment-tag: deploy-preview
          mode: recreate
