name: Create GitHub App Token

on:
  workflow_call:
    outputs:
      token:
        description: 'The GitHub App installation token'
        value: ${{ jobs.create-token.outputs.token }}

jobs:
  create-token:
    runs-on: ubuntu-24.04-arm
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}