name: Generate Release Note Body
description: リリースノート本文を生成

inputs:
  version:
    description: v無しバージョン
    required: true
  github-token:
    description: GitHub トークン
    required: false
    default: ${{ github.token }}

outputs:
  body:
    description: 生成されたリリースノート本文'
    value: ${{ steps.generate.outputs.result }}

runs:
  using: composite
  steps:
    - name: Generate release note body
      id: generate
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          const { data: { body } } = await github.rest.repos.generateReleaseNotes({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${{ inputs.version }}`,
          });
          return body;

    - name: Set output
      env:
        RELEASE_NOTES: ${{ steps.generate.outputs.result }}
      run: |
        {
          echo "body<<EOF"
          echo "$RELEASE_NOTES"
          echo "EOF"
        } >> $GITHUB_OUTPUT
      shell: bash
